import {listTransactions,exportTransactions} from '../src/transactions';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {afterEach,expect,it,vi} from 'vitest';
import {createPersonalGift,addPersonalMovement,sendPersonalGift,personalGiftRoute,personalGiftStatements} from '../src/personal-gifts';
import {receiveDistributionStatus} from '../src/distribution';
const dbs:DatabaseSync[]=[];afterEach(()=>dbs.splice(0).forEach(d=>d.close()));
const contact={id:'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',first_name:'Original',last_name:'Donor',email:'donor@example.test',phone:'9725550100'};
function setup(){const db=new DatabaseSync(':memory:');dbs.push(db);for(const f of readdirSync('migrations').filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync('migrations/'+f,'utf8'));
class S{v:any[]=[];constructor(public sql:string){}bind(...v:any[]){this.v=v;return this;}async first(){return db.prepare(this.sql).get(...this.v)||null;}async all(){return {results:db.prepare(this.sql).all(...this.v)};}async run(){return {meta:{changes:Number(db.prepare(this.sql).run(...this.v).changes)}};}}
const files=new Map();const env={SHARED_SIGNIN:'enabled',DB:{prepare:(s:string)=>new S(s),batch:async(ss:S[])=>{db.exec('BEGIN');try{const r=[];for(const s of ss)r.push(await s.run());db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}},IDENTITY:{fetch:vi.fn(async()=>Response.json({contacts:[contact]}))},HOPE_ADMIN:{fetch:vi.fn(async()=>Response.json({status:'pending'}))},CSM_DISTRIBUTION_SECRET:'test-secret',LEDGER_ATTACHMENTS:{put:vi.fn(async(k:string,b:unknown)=>files.set(k,b)),delete:vi.fn(async(k:string)=>files.delete(k)),get:vi.fn(async(k:string)=>files.has(k)?{body:files.get(k)}:null)}} as unknown as Env;
const key=crypto.randomUUID(),body={id:key,donorId:contact.id,receivedBy:'Brent Kern',method:'Personal Venmo',giftDate:'2026-09-23',amountCents:25000,reference:'payment-'+key,designation:'Hope Sojourns',note:'Mission gift',ministryGiftConfirmed:true};return{db,env,key,body};}
const req=(b:unknown)=>new Request('https://example.test/api/admin/personal-gifts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});
const transfer=(revision=1,amountCents=25000)=>({id:crypto.randomUUID(),revision,kind:'transfer',date:'2026-09-23',amountCents,reference:'bank-batch-1',description:'CSM checking',clearedDate:'2026-09-24'});
it('records the selected donor separately from the holder; original save retries do not duplicate',async()=>{const f=setup();await createPersonalGift(req(f.body),f.env,'reviewer');await createPersonalGift(req(f.body),f.env,'reviewer');const g=f.db.prepare('SELECT * FROM personal_gifts').get()!;expect(g.donor_id).toBe(contact.id);expect(g.received_by).toBe('Brent Kern');expect(f.db.prepare('SELECT count(*) n FROM personal_gifts').get()?.n).toBe(1);await expect(createPersonalGift(req({...f.body,amountCents:100}),f.env,'reviewer')).rejects.toMatchObject({status:409});});
it('requires explicit ministry intent and authorized HS contact lookup',async()=>{const f=setup();await expect(createPersonalGift(req({...f.body,ministryGiftConfirmed:false}),f.env,'x')).rejects.toMatchObject({status:422});vi.mocked(f.env.IDENTITY!.fetch).mockResolvedValue(Response.json({error:'No HS access'},{status:403}));await expect(createPersonalGift(req(f.body),f.env,'x')).rejects.toMatchObject({status:403});expect(f.db.prepare('SELECT count(*) n FROM personal_gifts').get()?.n).toBe(0);});
it('tracks partial transfers, rejects over-allocation and stale writes, and safely retries a movement',async()=>{const f=setup();await createPersonalGift(req(f.body),f.env,'x');const m=transfer(1,10000);await addPersonalMovement(req(m),f.env,f.key,'x');await addPersonalMovement(req(m),f.env,f.key,'x');await expect(addPersonalMovement(req(transfer(1,100)),f.env,f.key,'x')).rejects.toMatchObject({status:409});await expect(addPersonalMovement(req(transfer(2,20000)),f.env,f.key,'x')).rejects.toMatchObject({status:409});await expect(sendPersonalGift(req({revision:2}),f.env,f.key,'x')).rejects.toMatchObject({status:422});const r=await (await personalGiftRoute(new Request('https://example.test/personal-gifts'),f.env,'/personal-gifts','x')).json() as any;expect(r.gifts[0].remainingCents).toBe(15000);});
it('one combined bank deposit can allocate separately to two original donors',async()=>{const f=setup();await createPersonalGift(req(f.body),f.env,'x');const secondContact={...contact,id:crypto.randomUUID(),first_name:'Another'};vi.mocked(f.env.IDENTITY!.fetch).mockResolvedValue(Response.json({contacts:[secondContact]}));const second={...f.body,id:crypto.randomUUID(),donorId:secondContact.id,reference:'second-gift'};await createPersonalGift(req(second),f.env,'x');await addPersonalMovement(req(transfer()),f.env,f.key,'x');await addPersonalMovement(req(transfer()),f.env,second.id,'x');expect(f.db.prepare('SELECT sum(amount_cents) n FROM personal_gift_movements').get()?.n).toBe(50000);});
it('freezes source records before sending; delivery retry retains identical identity and donor',async()=>{const f=setup();await createPersonalGift(req(f.body),f.env,'x');await addPersonalMovement(req(transfer()),f.env,f.key,'x');vi.mocked(f.env.HOPE_ADMIN.fetch).mockRejectedValueOnce(new Error('timeout'));await expect(sendPersonalGift(req({revision:2}),f.env,f.key,'x')).rejects.toMatchObject({status:503});await sendPersonalGift(req({revision:2}),f.env,f.key,'x');const calls=vi.mocked(f.env.HOPE_ADMIN.fetch).mock.calls;expect(calls[0]![1]!.body).toBe(calls[1]![1]!.body);const sent=JSON.parse(String(calls[1]![1]!.body));expect(sent.displayName).toBe('Original Donor');expect(sent.personalGift.receivedBy).toBe('Brent Kern');expect(sent.destination).toBe('HopeSojourns');expect(f.db.prepare('SELECT count(*) n FROM paypal_transactions').get()?.n).toBe(0);await expect(addPersonalMovement(req(transfer(3,1)),f.env,f.key,'x')).rejects.toMatchObject({status:409});});
it('approval callback credits original donor in statements and ignores transfer-agent credit',async()=>{const f=setup();await createPersonalGift(req(f.body),f.env,'x');await addPersonalMovement(req(transfer()),f.env,f.key,'x');await sendPersonalGift(req({revision:2}),f.env,f.key,'x');expect(await personalGiftStatements(f.env,'2026')).toHaveLength(0);const r=await receiveDistributionStatus(new Request('https://internal/status',{method:'POST',headers:{'X-CSM-Distribution-Secret':'test-secret'},body:JSON.stringify({idempotencyKey:'HopeSojourns:personal:'+f.key,status:'approved',recordId:'hs-record'})}),f.env);expect(r.status).toBe(200);expect((await personalGiftStatements(f.env,'2026'))[0]).toMatchObject({counterpartyName:'Original Donor',gross:250,paymentMethod:'Personal Venmo'});});
it('voids unused errors and reverses settlement errors with durable audit history',async()=>{const f=setup();await createPersonalGift(req(f.body),f.env,'x');const m=transfer();await addPersonalMovement(req(m),f.env,f.key,'x');await personalGiftRoute(req({revision:2,reason:'Wrong deposit',movementId:m.id}),f.env,'/personal-gifts/'+f.key+'/reverse','x');await personalGiftRoute(req({revision:3,reason:'Wrong gift'}),f.env,'/personal-gifts/'+f.key+'/void','x');expect(f.db.prepare('SELECT voided FROM personal_gifts').get()?.voided).toBe(1);expect(f.db.prepare('SELECT count(*) n FROM personal_gift_history').get()?.n).toBe(4);});
it('requires original screenshot when there is no transaction reference and rejects unsupported files',async()=>{const f=setup();await createPersonalGift(req({...f.body,reference:''}),f.env,'x');await addPersonalMovement(req(transfer()),f.env,f.key,'x');await expect(sendPersonalGift(req({revision:2}),f.env,f.key,'x')).rejects.toMatchObject({code:'EVIDENCE_REQUIRED'});await expect(personalGiftRoute(new Request('https://example.test/files',{method:'POST',body:'not an image'}),f.env,'/personal-gifts/'+f.key+'/files','x')).rejects.toMatchObject({status:422});});

it('stores private evidence and reconciles fees and expenses before delivery',async()=>{const f=setup();await createPersonalGift(req({...f.body,reference:''}),f.env,'x');const path='/personal-gifts/'+f.key;const response=await personalGiftRoute(new Request('https://example.test/files',{method:'POST',headers:{'x-file-name':'proof.pdf'},body:'%PDF-1.7 sample test evidence'}),f.env,path+'/files','x');expect(response.status).toBe(201);const file=await response.json() as any;const download=await personalGiftRoute(new Request('https://example.test/files'),f.env,path+'/files/'+file.id,'x');expect(download.headers.get('Cache-Control')).toContain('private');expect(await download.text()).toContain('%PDF-');await addPersonalMovement(req({...transfer(2,500),kind:'fee'}),f.env,f.key,'x');await addPersonalMovement(req({...transfer(3,2000),kind:'expense'}),f.env,f.key,'x');await addPersonalMovement(req(transfer(4,22500)),f.env,f.key,'x');await sendPersonalGift(req({revision:5}),f.env,f.key,'x');const sent=JSON.parse(String(vi.mocked(f.env.HOPE_ADMIN.fetch).mock.calls[0]![1]!.body));expect(sent.transaction).toMatchObject({gross:250,fee:-5,net:245});expect(sent.personalGift.movements).toHaveLength(3);});

it('lists personal gifts with PayPal payments, filters and paginates them, without duplicating income',async()=>{
 const f=setup();f.body.giftDate=String(new Date().getUTCFullYear())+'-09-23';await createPersonalGift(req(f.body),f.env,'reviewer');
 const insert=f.db.prepare("INSERT INTO paypal_transactions(id,transaction_id,event_code,transaction_date,type,status,direction,currency,gross,fee,net,product_detected,raw_json,first_seen_at,last_seen_at) VALUES(?,?,'T0006',?,'Payment','Completed','received','USD',5,0,5,'HopeSojourns','{}','2026','2026')");
 for(let i=0;i<101;i++)insert.run('paypal-'+i,'reference-'+i,f.body.giftDate+'T10:00:00.000Z');
 const list=async(query='')=>await (await listTransactions(f.env,new URL('https://example.test/transactions'+query))).json() as any;
 const first=await list();expect(first.pagination).toMatchObject({total:102,pages:2});expect(first.transactions).toHaveLength(100);
 expect(first.transactions[0]).toMatchObject({id:'personal:'+f.key,personalGiftId:f.key,source:'personal',gross:250,remainingCents:25000,personalDeliveryStatus:'not_sent',displayName:'Original Donor'});
 expect(first.summary.total).toBe(755);expect(first.summary.donationCount).toBe(102);
 expect((await list('?page=2')).transactions).toHaveLength(2);
 expect((await list('?activity=personal')).pagination.total).toBe(1);
 expect((await list('?activity=bank_transfers')).pagination.total).toBe(0);
 expect((await list('?product=JoshBeyondBorders')).pagination.total).toBe(0);
 expect((await list('?direction=sent')).pagination.total).toBe(0);
 expect((await list('?search=donor%40example.test')).pagination.total).toBe(1);
 expect((await list('?year=2020')).pagination.total).toBe(0);
 const exported=await (await exportTransactions(f.env)).json() as any;expect(exported.transactions).toHaveLength(102);
 expect(f.db.prepare('SELECT count(*) n FROM paypal_transactions').get()?.n).toBe(101);
 await expect(sendPersonalGift(req({revision:1}),f.env,f.key,'reviewer')).rejects.toMatchObject({code:'UNSETTLED_GIFT'});
 await addPersonalMovement(req({...transfer(),date:f.body.giftDate,clearedDate:f.body.giftDate}),f.env,f.key,'reviewer');
 expect((await list('?activity=personal')).transactions[0].remainingCents).toBe(0);
 await sendPersonalGift(req({revision:2}),f.env,f.key,'reviewer');await sendPersonalGift(req({revision:2}),f.env,f.key,'reviewer');
 expect((await list('?activity=personal')).transactions[0]).toMatchObject({personalDeliveryStatus:'pending',personalLocked:1});
 expect((await list()).summary.total).toBe(755);expect(f.db.prepare('SELECT count(*) n FROM personal_gifts').get()?.n).toBe(1);
});
it('keeps voided personal gifts visible for audit while excluding them from giving totals',async()=>{
 const f=setup();f.body.giftDate=String(new Date().getUTCFullYear())+'-09-23';await createPersonalGift(req(f.body),f.env,'reviewer');
 await personalGiftRoute(req({revision:1,reason:'Incorrect test entry'}),f.env,'/personal-gifts/'+f.key+'/void','reviewer');
 const result=await (await listTransactions(f.env,new URL('https://example.test/transactions'))).json() as any;
 expect(result.transactions[0].status).toBe('Voided');expect(result.summary.total).toBe(0);
});
